version: "3.7"
services:
    sicp:
        build:
            context: ./docker/sicp
            dockerfile: Dockerfile
        volumes:
            - ./:/sicp
    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        volumes:
        -  ./:/sicp